CREATE TABLE BUG (
    BUG_ID BIGINT NOT NULL AUTO_INCREMENT,
    BUG_TITLE VARCHAR(100) NOT NULL,
    BUG_PRIORITY VARCHAR(100) NOT NULL,
    BUG_CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    BUG_UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    BUG_STATUS VARCHAR(100) NOT NULL,
    BUG_AUTHOR BIGINT NOT NULL,
    BUG_DESCRIPTION VARCHAR(2000),
    BUG_ASSIGNED BIGINT NULL,
    PRIMARY KEY (BUG_ID),
    FOREIGN KEY (BUG_PRIORITY) REFERENCES BUG_PRIORITY(BUG_PRIORITY),
    FOREIGN KEY (BUG_STATUS) REFERENCES BUG_STATUS(BUG_STATUS),
    FOREIGN KEY (BUG_AUTHOR) REFERENCES USER(USER_ID),
    FOREIGN KEY (BUG_ASSIGNED) REFERENCES USER(USER_ID)
);