CREATE TABLE BUG_PRIORITY (
    BUG_PRIORITY_ID BIGINT NOT NULL AUTO_INCREMENT,
    BUG_PRIORITY VARCHAR(100),
    PRIMARY KEY (BUG_PRIORITY)
);

INSERT INTO BUG_PRIORITY (BUG_PRIORITY)
VALUES ('High'),
       ('Medium'),
       ('Low');