CREATE TABLE COMMENT (
    COMMENT_ID BIGINT NOT NULL,
    COMMENT_BUG BIGINT NOT NULL,
    COMMENT_AUTHOR BIGINT NOT NULL,
    COMMENT_BODY VARCHAR(2000),
    COMMENT_CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    COMMENT_UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY_KEY (COMMENT_ID),
    FOREIGN KEY (COMMENT_BUG) REFERENCES BUG(BUG_ID),
    FOREIGN KEY (COMMENT_AUTHOR) REFERENCES USER(USER_ID)
);